---
layout: post
title: javascript - Abstract Factory 예제
date: '2018-07-05T01:50:00.002-07:00'
author: schoolhompy
tags: 
modified_time: '2018-07-05T01:50:36.806-07:00'
blogger_id: tag:blogger.com,1999:blog-4954243635432022205.post-4134371702058685982
blogger_orig_url: https://yunhos.blogspot.com/2018/07/javascript-abstract-factory.html
---

var NpcFactory = (function(){<br />&nbsp; &nbsp; var npcList = [];<br />&nbsp; &nbsp; return {<br />&nbsp; &nbsp; &nbsp; &nbsp; addType : function(npcElement) {<br />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; if (npcList.indexOf(npcElement) &gt; -1) {<br />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; console.log("duplicated");<br />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; return;<br />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }<br />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; npcList.push(npcElement);<br />&nbsp; &nbsp; &nbsp; &nbsp; },<br />&nbsp; &nbsp; &nbsp; &nbsp; createNpc : function(npcElement, options) {<br />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; var Npc = npcList[npcList.indexOf(npcElement)];<br />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; return (Npc ? new Npc.npcElement(options) : null)<br />&nbsp; &nbsp; &nbsp; &nbsp; }<br />&nbsp; &nbsp; }<br />})();<br /><br />var enermyMagician = (function(){<br />&nbsp; &nbsp;function enermyMagician(options){<br />&nbsp; &nbsp; &nbsp; &nbsp;this.name = options.name;<br />&nbsp; &nbsp;}<br />&nbsp; &nbsp;enermyMagician.prototype.attack = function(target) {<br />&nbsp; &nbsp; &nbsp; &nbsp; console.log("big macic");<br />&nbsp; &nbsp; }<br />&nbsp; &nbsp;<br />&nbsp; &nbsp;return enermyMagician;<br /><br />})();<br /><br />var enermySword = (function(){<br />&nbsp; &nbsp;function enermySword(options){<br />&nbsp; &nbsp; &nbsp; &nbsp;this.name = options.name;<br />&nbsp; &nbsp;}<br />&nbsp; &nbsp;enermySword.prototype.attack = function(target) {<br />&nbsp; &nbsp; &nbsp; &nbsp; console.log("swing");<br />&nbsp; &nbsp; }<br />&nbsp; &nbsp;return enermySword;<br /><br />})();<br /><br />const npcOfMagician = {<br />&nbsp; &nbsp; npcType : 'magician',<br />&nbsp; &nbsp; npcElement : enermyMagician<br />};<br />const npcOfSword = {<br />&nbsp; &nbsp; npcType : 'sword',<br />&nbsp; &nbsp; npcElement : enermySword<br />};<br /><br />NpcFactory.addType(npcOfMagician);<br />NpcFactory.addType(npcOfSword);<br />var magic1 = NpcFactory.createNpc(npcOfMagician, { name: 'magic_1' });<br />var magic2 = NpcFactory.createNpc(npcOfMagician, { name: 'magic_2' });<br />var sword1 = NpcFactory.createNpc(npcOfSword, { name: 'sword_1' });<br /><br />console.log(magic1.attack());<br />console.log(magic2.name);<br /><div><br /></div>